[10.0][MIG] connector_job_subscribe
OCA/queue pull request #26
Opened 2017-09-12 12:26 UTC by sbidoul

2017-09-12 12:30 UTC, sbidoul commented
@Cedric-Pigeon @lmignon

2017-09-12 14:54 UTC, lmignon requested changes

2017-09-12 14:54 UTC, lmignon commented on queue_job_subscribe/views/res_users_view.xml
> +<openerp>
@sbidoul this file should be migrated to use the new conventions.

2017-09-12 19:00 UTC, sbidoul commented
@lmignon done

2017-09-13 06:20 UTC, lmignon approved these changes
@sbidoul Thank you for the migration

2017-09-13 06:55 UTC, Cedric-Pigeon approved these changes
Code review and tests

2017-09-13 07:57 UTC, simahawk approved these changes
LGTM. Just a small issue with a link in the README.

2017-09-13 07:57 UTC, simahawk commented on queue_job_subscribe/README.rst
> +   :alt: License: AGPL-3
this link sounds broken

2017-09-13 08:39 UTC, sbidoul commented
@simahawk I fixed that and improved the readme. Thanks for reviewing!

2017-09-13 08:41 UTC, simahawk commented
\o/

2017-09-14 12:12 UTC, merged