[FIX] queue_job: max retry
OCA/queue pull request #622
Opened 2024-01-28 14:06 UTC by oerp-odoo

When job fails because of concurrent update error, it does not respect max retries set by the job. Problem is ``perform`` method logic that handles re-try is never called, because ``runjob`` in controller that triggers jobs, catches expected exception and silences it. Though it is done to not pollute logs.

So for now, adding extra check before job is run, to make sure max retries are handled if it reached it.

2024-06-02 13:11 UTC, oerp-odoo commented
@guewen can you check this?

2024-06-03 14:09 UTC, amh-mw requested changes
Seems reasonable, but broad enough in scope that it should be covered by unit tests?

2025-01-28 12:17 UTC, simahawk commented on queue_job/controllers/main.py
> +        # FIXME: this exception never triggers up, so it never reaches
reason?

2025-01-28 12:57 UTC, oerp-odoo commented on queue_job/controllers/main.py
> +        # FIXME: this exception never triggers up, so it never reaches
If I remember correctly, there was other part of code that would catch an exception and then it would go into infinite retries (not knowing when to stop).

2025-12-01 05:47 UTC, AungKoKoLin1997 commented
I found this issue was happening in our customer environment.
@oerp-odoo Can you attend the comments?
I may work on that and supersede your PR if you don’t have time to follow it up.

@simahawk Can you please reopen the PR?

2025-12-02 06:05 UTC, oerp-odoo commented on queue_job/controllers/main.py
> +        # FIXME: this exception never triggers up, so it never reaches
Don't remember exact scenario how this would happen, but it would just keep running and retrying way past max retries, if let say concurrent update error would occur over and over again.

2026-05-17 13:26 UTC, closed without merging