[18.0][REF] queue_job: Use set.discard(...) instead of SafeSet
OCA/queue pull request #722
Opened 2024-12-17 08:14 UTC by florentx

2024-12-17 10:57 UTC, sbidoul approved these changes

2024-12-17 13:16 UTC, amh-mw requested changes
Why is the code coverage different on this pull request versus the other ones?

2024-12-21 16:16 UTC, sbidoul commented
/ocabot merge patch

2024-12-21 16:17 UTC, sbidoul commented
> Why is the code coverage different on this pull request versus the other ones?

Maybe the doc tests are not running anymore?

2024-12-21 16:20 UTC, merged