[11.0] [ADD] queue_nsca_client
OCA/queue pull request #78
Opened 2018-06-20 15:33 UTC by etobella

This addon allows to send information to your nsca server.

Configure
=========

* Access with developer mode
* Access *Settings / NSCA Client / Checks*
* Create all the checks you need for your queue system

The check must have the model *queue.job*, the method *cron_queue_status* and
the following arguments:
- domain: Domain to check (required)
- created_seconds: will only count the jobs older thant this seconds
- critical: Number of records that will mark the critical
- warning: Number of records that will mark the warning

For example, the arguments *[('state', '=', 'failed')], created_seconds=5, critical=2, warning=1*
will return ok if no jobs older than 5 seconds are failed, warning if only one
and otherwise it will return a critical.

The performance data will be the number of jobs found by the domain.

It depends on OCA/server-tools#1280.

2018-06-26 19:53 UTC, guewen commented
Interesting. I don't use nsca addons but seems legit. Just a thought: wouldn't make sense for the OCA to have a repository for all the NSCA addons (nsca_client and children)?

2018-06-26 21:15 UTC, etobella commented
It could be a good idea if more people are interested on nsca addons.
@sebalix

2019-03-07 09:23 UTC, pedrobaeza requested changes
Little things

2019-03-07 09:23 UTC, pedrobaeza commented on oca_dependencies.txt
> +server-tools-nsca https://github.com/etobella/server-tools 11.0-mig-nsca_client
Is this still needed?

2019-03-07 09:23 UTC, pedrobaeza commented on queue_nsca_client/__manifest__.py
> +    "data": [
Nitpicking: not needed

2019-03-07 09:23 UTC, pedrobaeza commented on queue_nsca_client/models/queue_job.py
> +            date = datetime.now() + timedelta(seconds=-created_seconds)
Use `fields.Datetime.from_string(fields.Datetime.now)` for tz consistency.

2019-03-07 09:23 UTC, pedrobaeza commented on queue_nsca_client/readme/CONFIGURE.rst
> +- domain: Domain to check (required)
Extra line for proper RST formatting

2019-06-27 13:28 UTC, jarroyomorales commented
@etobella Any progress with this?

2019-07-01 05:53 UTC, etobella commented
@pedrobaeza @jarroyomorales Comments attended

2019-07-01 07:08 UTC, guewen commented
> wouldn't make sense for the OCA to have a repository for all the NSCA addons (nsca_client and children)?

Any opinion on this @etobella @pedrobaeza @jarroyomorales ?

PSC-wise, it would make sense to have NSCA-addons grouped so the actors can take care of their addons in one repository.

2019-07-26 11:50 UTC, jarroyomorales commented on queue_nsca_client/models/queue_job.py
> +                fields.Datetime.now) + timedelta(seconds=-created_seconds)
missing parenthesis, `fields.Datetime.now()`

2019-08-26 09:42 UTC, jarroyomorales commented
> > wouldn't make sense for the OCA to have a repository for all the NSCA addons (nsca_client and children)?
> 
> Any opinion on this @etobella @pedrobaeza @jarroyomorales ?
> 
> PSC-wise, it would make sense to have NSCA-addons grouped so the actors using NSCA can take care of their addons in one repository.

I think it makes sense, +1

2020-09-18 10:02 UTC, jarroyomorales commented
@guewen @etobella @pedrobaeza If a nsca repo is not going to be created, can we try to get this module merged here? Thank you!

2021-10-31 12:20 UTC, closed without merging