[11.0][MIG] base_import_async and test_base_import_async
OCA/queue pull request #80
Opened 2018-06-21 13:49 UTC by tarteo

2018-06-22 06:05 UTC, astirpe requested changes
Works fine!

2018-06-22 06:05 UTC, astirpe commented on base_import_async/models/base_import_import.py
> +        fields = list(map(fix_import_export_id_paths, fields))
:trophy:

Just as information, this can also be written as: `fields = [fix_import_export_id_paths(f) for f in fields]`

2018-06-22 06:05 UTC, astirpe commented on base_import_async/models/base_import_import.py
> +    def _extract_records(self, model_obj, fields, data, chunk_size):
In this method `self` is not used. You can avoid to pass `self` by replacing the decorator with `@staticmethod`.

I would prefer to have this method renamed to `_extract_chunks()` or something else, so that is not overriding the one defined in the `BaseModel`: https://github.com/odoo/odoo/blob/1740b179bfa78dafe7094f1f090f4e42a2b13a5f/odoo/models.py#L878

2018-06-22 06:05 UTC, astirpe commented on base_import_async/readme/CONTRIBUTORS.rst
> +Other contributors include:
Your name is missing in the contributors list

2018-06-22 06:05 UTC, astirpe commented on base_import_async/readme/DESCRIPTION.rst
> +to import files in the background using the OCA/connector
OCA/queue

2018-06-22 06:05 UTC, astirpe commented on test_base_import_async/tests/test_base_import_async.py
> +class TestBaseImportConnector(common.TransactionCase):
TestBaseImportAsync

2018-06-22 06:05 UTC, astirpe commented on test_base_import_async/tests/test_base_import_async.py
> +###############################################################################
Shorten headers

2018-06-22 06:05 UTC, astirpe commented on test_base_import_async/tests/test_base_import_async.py
> +    def setUp(self):
This `def setUp()` is not very useful, is it?

2018-06-22 06:05 UTC, astirpe commented on base_import_async/models/base_import_import.py
> +        self.env['ir.attachment'].browse(att_id).write({
You can avoid to invoke this `browse()` by passing directly the attachment as parameter, instead of passing `att_id`.
The `att_id` is always generated by `_create_csv_attachment()`, so from `_create_csv_attachment()` you could return the `attachment` instead of `attachment.id`.

2018-06-22 06:05 UTC, astirpe commented on base_import_async/models/base_import_import.py
> +        att = self.env['ir.attachment'].browse(att_id)
You can avoid this `browse()` by passing the `attachment`, instead of `att_id`.

2018-06-22 06:05 UTC, astirpe commented on test_base_import_async/tests/data.xml
> +	<record id="testjournal" model="ir.model.data">
Please fix this:
```
test_base_import_async/tests/data.xml:3: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
test_base_import_async/tests/data.xml:4: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
test_base_import_async/tests/data.xml:11: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
test_base_import_async/tests/data.xml:18: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
```

2018-06-22 06:05 UTC, astirpe commented on base_import_async/README.rst
> -.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
The README.rst  is automatically overwritten by a cron script that runs during the night. Also that script is able to run over this module only after this PR is merged, so it will take a while. It means that, in the meanwhile, is better to restore the readme. This way it will also fix those 2 warnings:

```
************* Module base_import_async
base_import_async/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file. Template here: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
************* Module test_base_import_async
test_base_import_async/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file. Template here: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
```

2018-06-22 06:05 UTC, astirpe commented on base_import_async/readme/USAGE.rst
> +   `use_connector`, `chunk_size`).
`use_queue`

2018-06-22 06:05 UTC, astirpe commented on base_import_async/__manifest__.py
> +    'summary': 'This module extends the standard CSV import '
Such long texts in summaries are not displayed well in the kanban view of the addons.
A shorten summary would be preferable, something like:

```
Import CSV files in the background
```

2018-06-22 06:05 UTC, astirpe commented on test_base_import_async/__init__.py
> +###############################################################################
Use shorten headers

2018-06-22 06:46 UTC, astirpe commented
@casvissers you would be interested in this module

2018-06-22 11:03 UTC, tarteo commented on test_base_import_async/tests/test_base_import_async.py
> +    def setUp(self):
It's to make shortcuts to models.

2018-06-22 11:03 UTC, tarteo commented
@astirpe Thanks for your review! Can you check again, please :+1:

2018-06-22 11:13 UTC, astirpe commented on test_base_import_async/tests/test_base_import_async.py
> +    def setUp(self):
Are you insinuating that it is very useful? :thinking:

2018-06-22 11:30 UTC, tarteo commented on test_base_import_async/tests/test_base_import_async.py
> +    def setUp(self):
Yes :smile:

2018-06-22 11:46 UTC, astirpe approved these changes

2018-06-23 09:52 UTC, sbidoul reviewed
Thanks for this work! A couple of minor comments (documenting the API breakage is important, the other comments much less).

2018-06-23 09:52 UTC, sbidoul commented on base_import_async/readme/USAGE.rst
> +   `use_connector`, `chunk_size`).
@tarteo since this is an API breakage, could you add a readme/HISTORY.rst warning about it? That will save some pain to our future selves.

2018-06-23 09:52 UTC, sbidoul commented on base_import_async/models/base_import_import.py
> +        datas = encodebytes(f.getvalue().encode(encoding))
`base64.encodebytes` would be a tad easier to read.

2018-06-23 09:52 UTC, sbidoul commented on base_import_async/models/base_import_import.py
> +        decoded_datas = decodebytes(att.datas)
base64.decodebytes is more explicit

2018-06-23 09:52 UTC, sbidoul commented on base_import_async/models/base_import_import.py
> +        f = StringIO(decoded_datas.decode(encoding))
`f = io.TextIOWrapper(io.BytesIO(decoded_datas), encoding="utf8")` should be more memory efficient by decoding on the fly.

2018-06-26 13:47 UTC, tarteo commented
Hey @sbidoul thanks for your review! I've applied your suggestions. Can you recheck if it's OK, please?

2018-06-26 14:54 UTC, sbidoul approved these changes
Thanks!

2018-06-26 19:48 UTC, guewen reviewed
Thanks! :star2:

2018-06-26 19:50 UTC, merged